# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex -direct -load *.tcl" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded XMLCommunication 1.6.7 [list source [file join $dir XMLCommunication.tcl]]
package ifneeded Debug 1.6.7 [list source [file join $dir Debug.tcl]]
package ifneeded XMLConstants 1.6 [list source [file join $dir XMLConstants.tcl]]
package ifneeded Supports 1.6 [list source [file join $dir Supports.tcl]]
package ifneeded uuid 1.0.0 [list source [file join $dir uuid.tcl]]